### ISSUE TITLE
Release into ROS Jade

### ISSUE THREAD

**Issue by mikeferguson** [ros-gbp/bfl-release#8]
This is a dependency of the navigation stack, so we need to get it released, unfortunately, I went to release it this evening and found that the svn repo for upstream seems to be gone. Thats going to need to be dealt with....

**Comment by mikeferguson** [comment]
@wjwwood is there anyway in bloom to skip the recreating of the upstream tag and just proceed with releasing the same upstream tag into a new ROS distro?

**Comment by wjwwood** [comment]
Technically yes, I think if you edit the `tracks.yaml` file you can remove the export from upstream and import from archive steps, and it will just continue with the release as normal. Try removing these lines:

https://github.com/ros-gbp/bfl-release/blob/master/tracks.yaml#L63-L66

I haven't tried this though. It might not work.

**Comment by mikeferguson** [comment]
@wjwwood Thanks -- I'll try that and report back -- I know it was the export upstream command that was failing -- I didn't even think to try editing the tracks.yaml

**Comment by mikeferguson** [comment]
@wjwwood That appears to have worked! Thanks!

**Comment by wjwwood** [comment]
Yeah, I often lament over how complicated bloom ended up being, but sometimes it comes in handy.
